server:
  port: 8082

spring:
  application:
    name: ticket-publisher
  activemq:
    broker-url: tcp://localhost:61616
    username: admin
    password: admin
    packages:
      trust-all: true
    topic:
      ticket-for-processing: jms.topic.ticketForProcessing
  jms:
    listener:
      acknowledge-mode: auto
      auto-startup: true
    template:
      default-destination:
      delivery-mode: non_persistent
      priority: 100
      qos-enabled: true
      receive-timeout: 1000
      time-to-live: 3600000